language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libtcd0
install:
  - pip install . pytest pytest-cov
script:
  - py.test --cov=libtcd --cov-report=
  - coverage report --show-missing --fail-under=100
